Feature/db data
Social-projects-Rivne/Rv-026WebUI pull request #3
Opened 2017-08-19 16:31 UTC by LischukAndry

pginit.js - script that creates tables and references between them. Also, this script  fills in tables with test data.

How to use:

1. configure config.js;
2. build project (npm run start);
3. run script (npm run pg init);

Now you have this tables in your local db:
![screenshot from 2017-08-19 19-28-29](https://user-images.githubusercontent.com/14792398/29488468-9bf3ee72-8514-11e7-81b7-a3ea628fe9f3.png)

2017-08-21 11:23 UTC, iuriifaevskii approved these changes

2017-08-21 12:29 UTC, python4eg commented on helpers/pginit.js
> +const conString = `postgres://${config.userName}:${config.password}@${config.dbServerLocation}:${config.serverPort}/${config.dbName}`;
db creation and initialization should be separate tasks

2017-08-21 12:31 UTC, python4eg commented on helpers/pginit.js
> +client.query(`CREATE TABLE IF NOT EXISTS users(
please read about query `on` and `end` methods

2017-08-21 12:31 UTC, python4eg commented on helpers/pginit.js
> +client.query(`CREATE TABLE IF NOT EXISTS users(
error handling

2017-08-21 12:32 UTC, python4eg commented on helpers/pginit.js
> +client.query(`INSERT INTO users (fullname, userrole,passhesh, salt, email, is_premium, phone_number, is_deleted, avatar, aboutMe) VALUES
all data should be stored as a separate object

2017-08-21 12:33 UTC, python4eg commented on helpers/pginit.js
> +    is_deleted      boolean       NOT NULL,
nitpick: change with: `retire_date` to monitor when user's been retired/deleted

2017-08-21 12:35 UTC, python4eg commented on helpers/pginit.js
> +    avatar          varchar(100),
nice to have: change with `gravatar`

2017-08-21 12:36 UTC, python4eg commented on helpers/pginit.js
> +    is_premium      boolean       NOT NULL,
change with type and create separate table with use types

2017-08-21 12:37 UTC, python4eg commented on helpers/pginit.js
> +    userrole        varchar(20)   NOT NULL,
should be int and points to another table with all roles by id

2017-08-21 12:38 UTC, python4eg commented on helpers/pginit.js
> +client.query(`CREATE TABLE IF NOT EXISTS registartion(
shy do we need this table?

2017-08-21 12:38 UTC, python4eg commented on helpers/pginit.js
> +)`);
please add postgresql like description to each field for all tables

2017-08-21 12:39 UTC, python4eg commented on helpers/pginit.js
> +    is_deleted      boolean         NOT NULL,
add default value as FALSE

2017-08-21 12:39 UTC, python4eg commented on helpers/pginit.js
> +    name         varchar(30)    UNIQUE      NOT NULL
tag description

2017-08-21 12:40 UTC, python4eg commented on helpers/pginit.js
> +client.query(`CREATE TABLE IF NOT EXISTS resipe_tag(
why do we need this extra layer?

2017-08-21 12:41 UTC, python4eg requested changes
please find all my comments above

2017-08-21 21:08 UTC, LischukAndry commented on helpers/pginit.js
> +const conString = `postgres://${config.userName}:${config.password}@${config.dbServerLocation}:${config.serverPort}/${config.dbName}`;
Do you mean I should create a separate method for each task, or create a new script file for "initialization"?

2017-08-21 22:47 UTC, LischukAndry commented on helpers/pginit.js
> +client.query(`CREATE TABLE IF NOT EXISTS registartion(
@python4eg One of the team members asks me to add this table for saving data about users who registered but don't confirm the email address. But now I think we can save this data in table users with a default value of field `is_deleted` as TRUE and when user confirm his email address, then change this value. Isn't it?

2017-08-21 23:01 UTC, LischukAndry commented on helpers/pginit.js
> +    name         varchar(30)    UNIQUE      NOT NULL
@python4eg What do you mean? Should I rename `name` like `tag description` or add a new field?

2017-08-22 17:07 UTC, LischukAndry commented on helpers/pginit.js
> +client.query(`CREATE TABLE IF NOT EXISTS resipe_tag(
@python4eg  We need this table for creating many-to-many relationship.

2017-08-29 20:57 UTC, merged